### ISSUE TITLE
Can we convert the .class by function level ?

### ISSUE THREAD

**Issue by gzthinkland** [radioegor146/native-obfuscator#33]
Can we convert the .class by function level ?
If yes, how can we realize it ?

**Comment by radioegor146** [comment]
It is probably possible for some functions, however the idea of this converter was to create code that will be identical to java bytecode. Nevertheless, if you want to create some way of true AoT compilation, at least you need to create a decent garbage collector and implement some functions in pure C/C++.

**Comment by Zaxar163** [comment]
First question is what GC is better (mark and sweep in CPP is impplemented in 3 libraries) Mark and sweep? custom?

**Comment by radioegor146** [comment]
Added text to README on how to filter specific functions.
