### ISSUE TITLE
Can i use this in the android project?

### ISSUE THREAD

**Issue by 751643992** [radioegor146/native-obfuscator#35]
Because in the android project the final code is smali code, and i want use this translate java code to native code.

**Comment by radioegor146** [comment]
Well, you can do some stuff in java, then compile it and translate to CPP. Then you can compile it with CMake for arm and use as a native library.

**Comment by 751643992** [comment]
Your meant is if I don't make any changes, use this in the android project will be crash?

**Comment by 751643992** [comment]
fatal error: 'jvmti.h' file not found，i use this in my android project,get above error,because android has not jvmti.h below android 9.

**Comment by libYo** [comment]
I test with android 5 working fine,.
