### ISSUE TITLE
Hello, can I use it on Android platform?

### ISSUE THREAD

**Issue by udochina** [radioegor146/native-obfuscator#40]
Hello, I hope I can use it on Android platform to ensure the security of Java code. Is that ok?

**Comment by Zaxar163** [comment]
Why your need it? Describe your problem. You can crosscompile c++ for ARM platform.

**Comment by udochina** [comment]
Thank you. I have solved the related problems and successfully applied them to Android to protect my java code with ollvm.

**Comment by 751643992** [comment]
@udochina Hello, i have the same problem. How can I contact you？
