### ISSUE TITLE
Can you tell me how to make a .dll file?

### ISSUE THREAD

**Issue by doodooaw** [radioegor146/native-obfuscator#47]
Tell me how to make a .dll file or how to run the program? So I got a jar file, then there is a cpp folder for me, what do I need to do in dll right away? Tell me please

**Comment by Rabbit0w0** [comment]
cmake

**Comment by ItzRiotz** [comment]
cmake then open in visual studio and build.. it'll output in ./build/lib

**Comment by TheiluhaYT** [comment]
> cmake затем откройте в Visual Studio и создайте .. он будет выводиться в ./build/lib

can minecraft be used?

**Comment by ItzRiotz** [comment]
> can minecraft be used?
I am trying to partially utilize it, but from what I've experienced any file operations will throw an exception_access_violation.
I'd highly doubt you can totally obfuscate Minecraft with this seeing as it's converting bytecode to C++ and Minecraft is made to work in Java (despite OpenGL being native C++, it still uses the LWJGL wrapper).
Would discourage trying :)

**Comment by ItzRiotz** [comment]
@redstonepro109 HeyaGlitz#6299

**Comment by radioegor146** [comment]
> 

Btw can you post your results about doing it? I can probably work on them now.

**Comment by radioegor146** [comment]
Added to README on how to do it.
