### ISSUE TITLE
x64 dll

### ISSUE THREAD

**Issue by HeyaGlitz** [radioegor146/native-obfuscator#48]
is it possible to build a x64 bit dll instead of 32 bit, how would I go about doing this?
(simply changing from Win32 to x64 gives problems with JNI imports, I somewhat lack knowledge in problem solving in C++)

**Comment by Rabbit0w0** [comment]
it appears not possible

**Comment by ItzRiotz** [comment]
@radioegor146 what do you think?

**Comment by radioegor146** [comment]
@HeyaGlitz Can you post your logs?

**Comment by radioegor146** [comment]
It's possible, you may need to install x64 JDK.
