### ISSUE TITLE
Поделить проект.

### ISSUE THREAD

**Issue by Zaxar163** [radioegor146/native-obfuscator#5]
Для isn групп - свои классы.

**Comment by radioegor146** [comment]
Да вообще надо отрефакторить по хорошему. Но я бы всё равно предпочёл использовать ASM Tree API.

**Comment by Zaxar163** [comment]
С рефакторингом - как доделаем разберусь. Есть пара идеек по этому поводу. 
```java
publiic interface Acceptor {
int[] opcodes();
void accept(IsnNode n);
```

**Comment by Zaxar163** [comment]
#17 #16
