### ISSUE TITLE
JDK 11+ java.lang.NoSuchMethodError: linkCallSite

### ISSUE THREAD

**Issue by mdxd44** [radioegor146/native-obfuscator#58]
При запуске приложения на 11 джаве и выше возникает ошибка: java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: linkCallSite

jdk 10
![изображение](https://user-images.githubusercontent.com/67416904/170526969-93b13266-88c2-4506-9b51-2b4afd167d56.png)
jdk 11 в которой появился int (не ясно зачем, [первое появление](https://github.com/openjdk/jdk11/commit/e55a05957d06b869a6d26a5b49e253a015f278da#diff-1226d42ed977e662aabceccf7ada81a71e693360aa79aa84f5b193a40470c15fL230))
![изображение](https://user-images.githubusercontent.com/67416904/170527129-697ca23d-8533-46e3-acb9-010b8a531538.png)

**Comment by radioegor146** [comment]
Хмм, я пока что заявляю поддержку только JDK8. Пока что должен работать флаг `-platform std_java`.
Гляну когда смогу.

**Comment by radioegor146** [comment]
Будет ли достаточно удобно это учитывать при компиляции? Или необходимо в рантайме?

**Comment by radioegor146** [comment]
BTW его убрали потом: https://bugs.openjdk.java.net/browse/JDK-8272614

**Comment by radioegor146** [comment]
As far as I've tested, it should work now on JDK11+ with `-platform hotspot`.

**Comment by mdxd44** [comment]
> Хмм, я пока что заявляю поддержку только JDK8. Пока что должен работать флаг `-platform std_java`. Гляну когда смогу.

Не работает кстати
![изображение](https://user-images.githubusercontent.com/67416904/171918373-e9f6948f-33f5-4e70-9b65-91ee4d6e0199.png)

**Comment by radioegor146** [comment]
Jar после обфускации? Этот шаг не менялся.

**Comment by mdxd44** [comment]
Без обфускации

**Comment by mdxd44** [comment]
Судя по NegativeArraySizeException ошибка может быть только [тут](https://github.com/radioegor146/native-obfuscator/blob/master/obfuscator/src/main/java/by/radioegor146/bytecode/IndyPreprocessor.java#L160)

**Comment by radioegor146** [comment]
Пробуй `-platform hotspot`

**Comment by mdxd44** [comment]
> Пробуй `-platform hotspot`

Работает, проверил на 17 джаве
