### ISSUE TITLE
issue with that "SYNTHETIC_LOCAL_VARIABLE" thing that i see in my decompiler.

### ISSUE THREAD

**Issue by cwoodard1121** [radioegor146/native-obfuscator#59]
Exception in thread "main" java.lang.VerifyError: Bad local variable type.
This comes after another error, when compiling the c++ it says that clocal0 is not defined, i added it as a jvalue but that gave me this other error. 

:\b\out\cpp\output\Main.cpp(137,9): error C2065: 'clocal0': undeclared identifier [C:\b\out\cpp\native_library.vcxproj]
C:\b\out\cpp\output\Main.cpp(137,38): error C2065: 'clocal0': undeclared identifier [C:\b\out\cpp\native_library.vcxproj]

**Comment by radioegor146** [comment]
Can you provide class file? Is VerifyError presented when running java only version?

**Comment by cwoodard1121** [comment]
by java only version, do you mean the version BEFORE I use the obfuscator? or after and just the jar. if you mean the second option, no. It does not happen. I will send both the pre obfuscation class file and post. Also, when compiling into a DLL the clocal0 variable is missing which could have something to do with this.
 https://github.com/cwoodard1121/JNI-Testing
Pre and post obfuscation classes, as well as the C++ file is in here.

**Comment by radioegor146** [comment]
Can you repeat that with the latest version of obfuscator from the beginning?
Also, if you'll attach CLI arguments that you provide to obfuscator, that will help.

**Comment by cwoodard1121** [comment]
Thank you so much, the newest update fixed the issue!
