### ISSUE TITLE
Unknown obfuscator error

### ISSUE THREAD

**Issue by micartey** [radioegor146/native-obfuscator#63]
The instructions in [Basic Usage](https://github.com/radioegor146/native-obfuscator#basic-usage) states:
- Copy result .dll/.so from build/libs/ to the specified in previous paragraph path.

The jar is written to the output folder, and I would put the binary inside the jar.  
(I put the binary `x64-linux.so` into `native0` as I use linux x64)

But that doesn't work...
I am greeted with the following exception:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void k.a(java.io.File, java.util.function.BiConsumer, java.util.function.Consumer)'
	at k.a(Native Method)
	at me.micartey.test.Main.main(Unknown Source)
```

I ran the following command:
```shell
java -jar obfuscator.jar target.jar out -a
```

**Comment by radioegor146** [comment]
So you put binary to the 'native0/x64-linux.so'?

**Comment by micartey** [comment]
Correct. I also copied the same binary to native0/amd64-linux.so to make sure

**Comment by radioegor146** [comment]
Can you send me obfuscated/unobfuscated jar files (you can DM me at any of https://re146.dev, or email to the github email address)?

**Comment by micartey** [comment]
I will, but that has to wait for a few weeks until I am back home.

**Comment by micartey** [comment]
It seems to be an obfuscation error.
Using it on a Hello World example works flawlessly :)

**Comment by radioegor146** [comment]
Nevertheless, I'll be pleased if you can give obfuscated/unobfuscated jar files, so I can work on it :)

**Comment by radioegor146** [comment]
So I'm closing the issue due to inactivity. 
If you ever encounter this bug, feel free to reopen it.
