### ISSUE TITLE
can I use clang to compile CPP?

### ISSUE THREAD

**Issue by wawlsl** [radioegor146/native-obfuscator#64]
can I use clang to compile CPP?

**Comment by micartey** [comment]
I think you can use everything that compiles the files as long as it compiles.
Saw a lot of people using zig to compile for different targets.
Would love to see that here as well

**Comment by radioegor146** [comment]
Yep, you can.
About zig - currently to support it, I have to implement or find some kind of hashset for pointer cleanups
