### ISSUE TITLE
Execute cmake. An error occurs

### ISSUE THREAD

**Issue by xxtx4399** [radioegor146/native-obfuscator#65]
I successfully ran java -jar native-obfuscator.jar
It gives me a cpp folder and jar file
when I try to type cmake .
it went wrong

```
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   The system can not find the file specified。


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

I want to know what should I do to make it work

**Comment by radioegor146** [comment]
Did you install compiler?

**Comment by radioegor146** [comment]
If you will get this error any time in the future - feel free to reopen issue, but for now I'm closing it.
