### ISSUE TITLE
After I used the command to generate the jar package, the hidden class was not generated.

### ISSUE THREAD

**Issue by BRYNHILDRINTHEDARKNESS** [radioegor146/native-obfuscator#73]
why?

**Comment by radioegor146** [comment]
Can you describe your problem more informational? And maybe consider adding samples so I can look at the problem itself.

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
OS:Win10

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
And execute the command java jar obfuscator.jar classes.jar ./out/

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
![image](https://github.com/radioegor146/native-obfuscator/assets/38870869/c660aeda-f70f-447f-bca6-26b118960ae8)
that's the result.
And this out/classes.jar don't have hidden.class

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
This is Loader.class
![image](https://github.com/radioegor146/native-obfuscator/assets/38870869/e5258381-fd16-4a14-abda-7dcb1b33e8ab)

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
This is Main.class
![image](https://github.com/radioegor146/native-obfuscator/assets/38870869/83310ca8-446e-400c-be8f-e1439cbaf71e)

There is hidden.class in Main.class but not in the dex file.
