### ISSUE TITLE
Minecraft plugin error

### ISSUE THREAD

**Issue by 1050TIt0p** [radioegor146/native-obfuscator#79]
I am using native-obfuscator for Spigot plugin, there was a problem
The plugin won't start and gives an error (https://pastebin.com/TiQgPZXh), the forums say to install the package via apt install, but since I'm making the plugin for sale, and some people use panel hosting for Minecraft where they can't enter linux commands, they can't do it.

On the virtual machine where I built the .so file everything works fine.

Is it even possible to fix this?

**Comment by PerroDev** [comment]
Im getting the same error, any fix?
